/**
 * Centralized TypeScript types for the entire application
 */

// Note: @/payload/payload-types will be auto-generated by Payload CMS on first run
// Uncomment the line below after running `npm run dev` for the first time



// ==================== PRODUCT TYPES ====================

export interface ProductVariant {
  id: string
  size?: string
  color?: string
  sku: string
  stock: number
  priceModifier?: number
  image?: string
}

export interface Product {
  id: string
  name: string
  slug: string
  price: number
  compareAtPrice?: number
  images: ProductImage[]
  variants?: ProductVariant[]
  category: Category
  tags?: Tag[]
  rating: number
  reviewCount: number
  stock: number
  badge?: string
  featured?: boolean
  onSale?: boolean
  description?: string
  specifications?: Record<string, string>
  seo?: {
    title: string
    description: string
    keywords?: string[]
  }
  arModelUrl?: string // URL to 3D model for AR preview
  bundleProducts?: BundleProduct[] // Frequently bought together
  shippingInfo?: ShippingInfo
  faqs?: FAQ[]
  vendor?: {
    id: string
    name?: string // For PLP/category pages (light serialization)
    businessName?: string // For PDP (full serialization)
    slug?: string // For PDP (full serialization)
  }
}

export interface ProductImage {
  url: string
  alt: string
  type: 'image' | 'video' | '360'
  thumbnail?: string
  videoUrl?: string // For video type
  frames?: string[] // For 360 type (array of frame URLs)
}

// ==================== CATEGORY TYPES ====================

export interface Category {
  id: string
  name: string
  slug: string
  description?: string
  image?: string
  parent?: {
    name: string
    slug: string
  }
  order?: number
  isActive: boolean
  productCount?: number
}

// ==================== ORDER TYPES ====================

export type OrderStatus = 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled'
export type PaymentStatus = 'pending' | 'paid' | 'failed' | 'refunded'
export type PaymentGateway = 'PAYSTACK' | 'FLUTTERWAVE'

export interface OrderItem {
  id?: string
  productId: string
  name: string
  productImage: string
  variant?: {
    size?: string
    color?: string
    sku: string
  }
  quantity: number
  price: number
  subtotal: number
}

export interface Address {
  firstName: string
  lastName: string
  line1: string
  line2?: string
  city: string
  postalCode: string
  country: string
  phone: string
  email?: string
  isDefault?: boolean
}

export interface SavedAddress extends Address {
  id: string
  userId: string
  isDefault: boolean
  createdAt: Date
  updatedAt: Date
}

export interface Order {
  id: string
  orderNumber: string
  userId: string
  items: OrderItem[]
  status: OrderStatus
  paymentStatus: PaymentStatus
  paymentReference?: string // Paystack reference ou Flutterwave tx_ref
  paymentGateway?: PaymentGateway
  paymentMetadata?: Record<string, unknown>
  subtotal: number
  shippingCost: number
  shippingTotal?: number
  tax: number
  taxTotal?: number
  discount: number
  total: number
  shippingAddress: Address
  billingAddress?: Address
  trackingNumber?: string
  estimatedDelivery?: {
    min: Date
    max: Date
  } | Date
  createdAt: Date
  updatedAt: Date
  couponCode?: string
  customer?: {
    firstName: string
    lastName: string
    email: string
  }
  shipping?: {
    method: string
    cost: number
    estimatedDelivery: Date
    address: Address
  }
  payment?: {
    type: PaymentMethod
    brand?: string
    last4?: string
  }
  shippingMethod?: string
  paymentType?: PaymentMethod
  paymentBrand?: string
  paymentLast4?: string
}

// ==================== USER TYPES ====================

export interface User {
  id: string
  email: string
  firstName?: string
  lastName?: string
  addresses?: Address[]
  loyaltyPoints?: number
  loyaltyLevel?: 'Bronze' | 'Silver' | 'Gold' | 'Platinum'
  recentlyViewed?: string[]
  searchHistory?: string[]
  totals?: {
    orders: number
    spent: number
  }
}

// ==================== REVIEW TYPES ====================

export interface Review {
  id: string
  productId: string
  userId: string
  userName: string
  userAvatar?: string
  rating: number
  title?: string
  comment: string
  images?: string[]
  verified: boolean
  helpful: number
  notHelpful: number
  createdAt: Date
  response?: {
    text: string
    respondedAt: Date
    respondedBy: string
  }
}

export interface ReviewStats {
  average: number
  total: number
  distribution: {
    5: number
    4: number
    3: number
    2: number
    1: number
  }
}

// ==================== FILTER TYPES ====================

export interface Filter {
  priceRange?: {
    min: number
    max: number
  }
  categories?: string[]
  brands?: string[]
  colors?: string[]
  sizes?: string[]
  rating?: number
  inStock?: boolean
  onSale?: boolean
}

export interface AvailableFilters {
  priceRange: {
    min: number
    max: number
  }
  categories: Array<{ id: string; name: string; count: number }>
  brands: Array<{ id: string; name: string; count: number }>
  colors: Array<{ value: string; name: string; count: number }>
  sizes: Array<{ value: string; count: number }>
}

export type SortOption = 'relevance' | 'price-asc' | 'price-desc' | 'rating' | 'newest' | 'bestseller'

// ==================== PLP TYPES ====================

export interface BreadcrumbItem {
  label: string
  href?: string
}

export interface QuickFilter {
  id: string
  label: string
  value: string
}

export interface CategoryHeroData {
  title: string
  description?: string
  image?: string
  productCount: number
  quickFilters?: QuickFilter[]
}

export interface FilterSection {
  id: string
  title: string
  isOpen: boolean
}

export interface PriceHistogramBin {
  min: number
  max: number
  count: number
}

export interface RecentlyViewedProduct {
  productId: string
  viewedAt: string
}

// ==================== SHIPPING TYPES ====================

export interface ShippingOption {
  id: string
  name: string
  price: number
  estimatedDays: number
  carrier?: string
  cutoffTime?: string
  description?: string
}

export interface ShippingInfo {
  options: Array<{
    name: string
    price: number
    estimatedDays: number
    description?: string
  }>
  freeShippingThreshold?: number
  internationalShipping: boolean
  returnPolicy: string
}

// Simplified product for bundle display
export interface BundleProductInfo {
  id: string
  name: string
  slug: string
  price: number
  images: Array<{ url: string; alt: string }>
}

export interface BundleProduct {
  product: Product | BundleProductInfo
  discount?: number // Percentage discount when bought together
}

export interface RelayPoint {
  id: string
  name: string
  address: string
  city: string
  postalCode: string
  distance: number
  openingHours?: string[]
  coordinates?: {
    lat: number
    lng: number
  }
}

export interface Store {
  id: string
  name: string
  address: string
  city: string
  postalCode: string
  distance: number
  phone?: string
  openingHours?: string[]
}

// ==================== PAYMENT TYPES ====================

export type PaymentMethod = 'card' | 'paypal' | 'apple-pay' | 'google-pay' | 'installments'

export interface PaymentIntent {
  id: string
  clientSecret: string
  amount: number
  currency: string
  status: string
}

// ==================== CART TYPES ====================

export interface CartItem {
  id: string
  productId: string
  name?: string
  productName?: string
  productSlug: string
  productImage: string
  image?: string
  price: number
  quantity: number
  variant?: {
    size?: string
    color?: string
    sku: string
  }
  stock: number
  badge?: string // Promotional badges (e.g., 'NEW', 'SALE')
  freeShipping?: boolean // Item qualifies for free shipping
  inStock?: boolean // Stock availability (optional for backward compatibility)
  maxQuantity?: number // Maximum quantity that can be ordered
  compareAtPrice?: number // Original price before discount
  category?: string
  brand?: string
}

export interface SavedForLaterItem extends CartItem {
  savedAt: Date
}

export interface CouponCode {
  code: string
  discount: number
  type: 'percentage' | 'fixed'
  scope: 'cart' | 'shipping' // Determines whether coupon applies to items or shipping
  minPurchase?: number
  expiresAt?: Date
}

export interface CartRecommendation {
  productId: string
  relevanceScore: number
  reason?: string // e.g., 'frequently bought together', 'similar category'
}

// ==================== SEARCH TYPES ====================

export interface SearchResults {
  products: Product[]
  brands: Array<{ id: string; name: string; logo?: string }>
  articles: Array<{
    id: string
    title: string
    excerpt: string
    image?: string
    url: string
  }>
  videos: Array<{
    id: string
    title: string
    thumbnail: string
    duration: string
    url: string
  }>
}

// ==================== FAQ TYPES ====================

export interface FAQ {
  id: string
  question: string
  answer: string
  category: string
  order: number
  views: number
  helpful: number
  notHelpful: number
  relatedFAQs?: string[]
}

export interface FAQCategory {
  id: string
  name: string
  icon: string
  count: number
}

export interface QA {
  id: string
  question: string
  answer: string // Kept for backward compatibility with FAQ data
  helpful: number
  notHelpful?: number
  createdAt?: Date
  // Enhanced Q&A fields
  author?: {
    name: string
    avatar?: string
  }
  answers?: Array<{
    id: string
    text: string
    author: {
      name: string
      avatar?: string
    }
    isOfficial: boolean
    createdAt: Date
    helpful: number
    notHelpful: number
  }>
  askedAt?: Date
  verified?: boolean // Verified purchase question
}

// ==================== TAG TYPES ====================

export interface Tag {
  id: string
  name: string
  slug: string
}

// ==================== GAMIFICATION TYPES ====================

export interface LoyaltyTier {
  name: 'Bronze' | 'Silver' | 'Gold' | 'Platinum'
  pointsRequired: number
  benefits: string[]
}

// ==================== API RESPONSE TYPES ====================

export interface ApiResponse<T> {
  data: T
  success: boolean
  error?: string
}

export interface PaginatedResponse<T> {
  data: T[]
  totalCount: number
  page: number
  pageSize: number
  hasMore: boolean
}

// ==================== HEADER TYPES ====================

export interface HeaderConfig {
  heights: {
    promotionalBanner: number
    topBar: number
    mainHeader: number
    categoryNavBar: number
    total: number
    compact: number
  }
  scrollThresholds: {
    hide: number
    compact: number
  }
}

export interface Language {
  code: string
  name: string
  nativeName: string
  flag: string
}

export interface Currency {
  code: string
  symbol: string
  name: string
  rate: number
}

export interface RotatingMessage {
  id: string
  text: string
  icon?: string
  link?: string
  type?: 'info' | 'success' | 'warning' | 'promo'
}

export interface Notification {
  id: string
  type: 'order' | 'promo' | 'system' | 'message'
  title: string
  message: string
  icon?: string
  timestamp: Date
  read: boolean
  link?: string
}

export interface GeolocationData {
  country: string
  city: string | null
  region: string | null
  countryCode: string
  currency: string
  timezone: string
}

export interface UserPreferences {
  language: string
  currency: string
  theme: 'light' | 'dark' | 'system'
  location?: string
  notifications?: boolean
  reducedMotion?: boolean
}

export interface ComparatorItem {
  id: string
  name: string
  price: number
  image: string
  category: string
  addedAt: Date
}

export interface MegaMenuColumn {
  id: string
  title: string
  icon?: string
  description?: string
  link: string
  image?: string
  subcategories?: {
    id: string
    title: string
    link: string
    items?: {
      id: string
      title: string
      link: string
      badge?: string
    }[]
  }[]
}

export interface SearchFilters {
  query: string
  category?: string
  minPrice?: number
  maxPrice?: number
  inStock?: boolean
  sortBy?: 'relevance' | 'price-asc' | 'price-desc' | 'newest' | 'rating'
}

export interface SearchSuggestion {
  type: 'product' | 'category' | 'brand' | 'keyword'
  title: string
  subtitle?: string
  image?: string
  link: string
}

export interface VisualSearchResult {
  confidence: number
  product: Product
}

// ==================== CHECKOUT TYPES ====================

export type CheckoutStep = 'shipping' | 'payment' | 'review'

export interface TrustBadge {
  icon: string
  title: string
  description: string
}

export interface ShippingFormData {
  firstName: string
  lastName: string
  email: string
  phone: string
  line1: string
  line2?: string
  city: string
  postalCode: string
  country: string
  saveAddress?: boolean
}

export interface PaymentFormData {
  cardNumber: string
  expiryDate: string
  cvv: string
  cardholderName: string
  saveCard?: boolean
  billingAddressSameAsShipping?: boolean
  billingAddress?: Address
}

export interface BillingAddressFormData extends Address {
  sameAsShipping: boolean
}

// ==================== PAYMENT GATEWAY TYPES ====================

export interface PaystackInitializeResponse {
  success: boolean
  gateway: 'PAYSTACK'
  reference: string
  authorization_url: string
  access_code: string
  amount?: number // For display
  metadata?: Record<string, unknown>
}

export interface FlutterwaveInitializeResponse {
  success: boolean
  gateway: 'FLUTTERWAVE'
  tx_ref: string
  link: string
  amount?: number // For display
  metadata?: Record<string, unknown>
}

export type PaymentInitializeResponse =
  | PaystackInitializeResponse
  | FlutterwaveInitializeResponse

// ==================== ORDER INITIALIZATION TYPES ====================

export interface OrderInitializePayload {
  items: Array<{
    productId: string
    variantId?: string
    quantity: number
  }>
  shippingAddress: Address
  billingAddress?: Address
  shippingOption?: string
  gateway?: PaymentGateway
  email?: string
  promoCode?: string
  orderId?: string // For updating existing provisional order
}

export interface OrderInitializeResponse {
  success: boolean
  orderId: string
  orderNumber: string
  totals: {
    subtotal: number // in cents
    shippingCost: number // in cents
    tax: number // in cents
    discount: number // in cents
    total: number // in cents
  }
  provisional: boolean
}

// ==================== PAYMENT INITIALIZATION TYPES ====================

export interface InitializePaymentPayload {
  items?: Array<{
    productId: string
    variantId?: string
    quantity: number
  }>
  shippingOption?: string
  email?: string
  orderId?: string // If provisional order already created
  gateway: PaymentGateway
  metadata?: Record<string, unknown>
}

// ==================== ORDER COMPLETION TYPES ====================

export interface OrderCompletePayload {
  paymentReference: string
  paymentGateway: PaymentGateway
  billingAddress?: Address
  promoCode?: string
}

export interface OrderCompleteResponse {
  success: boolean
  orderId: string
  orderNumber: string
  status: OrderStatus
  paymentStatus: PaymentStatus
  message?: string
}

// ==================== WEBHOOK TYPES ====================

export interface InitializePaymentResponse {
  success: boolean
  gateway: 'PAYSTACK' | 'FLUTTERWAVE'
  reference?: string // Paystack reference
  authorization_url?: string // Paystack redirect URL
  tx_ref?: string // Flutterwave transaction reference
  link?: string // Flutterwave payment link
  amount: number
  orderId?: string
  error?: string
}

export interface WebhookMetadata {
  orderId?: string
  userId?: string
  items?: string // JSON string of cart items
  subtotal?: string
  shippingCost?: string
  tax?: string
  total?: string
  [key: string]: unknown
}

export interface PaystackWebhookEvent {
  event: string // e.g., 'charge.success', 'charge.failed'
  data: {
    reference: string
    amount: number // in kobo
    customer: {
      email: string
      [key: string]: unknown
    }
    metadata?: WebhookMetadata
    [key: string]: unknown
  }
}

export interface FlutterwaveWebhookEvent {
  event: string // e.g., 'charge.completed', 'charge.failed'
  data: {
    id: number | string
    tx_ref: string
    amount: number // in currency unit
    customer: {
      email?: string
      customer_email?: string
      phone?: string
      phone_number?: string
      [key: string]: unknown
    }
    meta?: WebhookMetadata
    metadata?: WebhookMetadata
    [key: string]: unknown
  }
}
