/**
 * Centralized TypeScript types for the entire application
 */

// Note: @/payload/payload-types will be auto-generated by Payload CMS on first run
// Uncomment the line below after running `npm run dev` for the first time
// import type { Media, Product as PayloadProduct, Category as PayloadCategory, Order as PayloadOrder, User as PayloadUser } from '@/payload/payload-types'

// ==================== PRODUCT TYPES ====================

export interface ProductVariant {
  id: string
  size?: string
  color?: string
  sku: string
  stock: number
  priceModifier?: number
  image?: string
}

export interface Product {
  id: string
  name: string
  slug: string
  price: number
  compareAtPrice?: number
  images: ProductImage[]
  variants?: ProductVariant[]
  category: Category
  tags?: Tag[]
  rating: number
  reviewCount: number
  stock: number
  badge?: string
  featured?: boolean
  onSale?: boolean
  description?: string
  specifications?: Record<string, string>
  seo?: {
    title: string
    description: string
    keywords?: string[]
  }
}

export interface ProductImage {
  url: string
  alt: string
  type: 'image' | 'video' | '360'
  thumbnail?: string
}

// ==================== CATEGORY TYPES ====================

export interface Category {
  id: string
  name: string
  slug: string
  description?: string
  image?: string
  parent?: string | Category
  order?: number
  isActive: boolean
  productCount?: number
}

// ==================== ORDER TYPES ====================

export type OrderStatus = 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled'
export type PaymentStatus = 'pending' | 'paid' | 'failed' | 'refunded'

export interface OrderItem {
  productId: string
  productName: string
  productImage: string
  variant?: {
    size?: string
    color?: string
    sku: string
  }
  quantity: number
  price: number
  subtotal: number
}

export interface Address {
  firstName: string
  lastName: string
  line1: string
  line2?: string
  city: string
  postalCode: string
  country: string
  phone: string
  email?: string
}

export interface Order {
  id: string
  orderNumber: string
  userId: string
  items: OrderItem[]
  status: OrderStatus
  paymentStatus: PaymentStatus
  subtotal: number
  shippingCost: number
  tax: number
  discount: number
  total: number
  shippingAddress: Address
  billingAddress?: Address
  trackingNumber?: string
  estimatedDelivery?: {
    min: Date
    max: Date
  }
  createdAt: Date
  updatedAt: Date
}

// ==================== USER TYPES ====================

export interface User {
  id: string
  email: string
  firstName?: string
  lastName?: string
  addresses?: Address[]
  loyaltyPoints?: number
  loyaltyLevel?: 'Bronze' | 'Silver' | 'Gold' | 'Platinum'
  recentlyViewed?: string[]
  searchHistory?: string[]
  totals?: {
    orders: number
    spent: number
  }
}

// ==================== REVIEW TYPES ====================

export interface Review {
  id: string
  productId: string
  userId: string
  userName: string
  userAvatar?: string
  rating: number
  title?: string
  comment: string
  images?: string[]
  verified: boolean
  helpful: number
  notHelpful: number
  createdAt: Date
  response?: {
    text: string
    respondedAt: Date
    respondedBy: string
  }
}

export interface ReviewStats {
  average: number
  total: number
  distribution: {
    5: number
    4: number
    3: number
    2: number
    1: number
  }
}

// ==================== FILTER TYPES ====================

export interface Filter {
  priceRange?: {
    min: number
    max: number
  }
  categories?: string[]
  brands?: string[]
  colors?: string[]
  sizes?: string[]
  rating?: number
  inStock?: boolean
  onSale?: boolean
}

export interface AvailableFilters {
  priceRange: {
    min: number
    max: number
  }
  categories: Array<{ id: string; name: string; count: number }>
  brands: Array<{ id: string; name: string; count: number }>
  colors: Array<{ value: string; name: string; count: number }>
  sizes: Array<{ value: string; count: number }>
}

export type SortOption = 'relevance' | 'price-asc' | 'price-desc' | 'rating' | 'newest' | 'bestseller'

// ==================== SHIPPING TYPES ====================

export interface ShippingOption {
  id: string
  name: string
  price: number
  estimatedDays: number
  carrier?: string
  cutoffTime?: string
  description?: string
}

export interface RelayPoint {
  id: string
  name: string
  address: string
  city: string
  postalCode: string
  distance: number
  openingHours?: string[]
}

export interface Store {
  id: string
  name: string
  address: string
  city: string
  postalCode: string
  distance: number
  phone?: string
  openingHours?: string[]
}

// ==================== PAYMENT TYPES ====================

export type PaymentMethod = 'card' | 'paypal' | 'apple-pay' | 'google-pay' | 'installments'

export interface PaymentIntent {
  id: string
  clientSecret: string
  amount: number
  currency: string
  status: string
}

// ==================== CART TYPES ====================

export interface CartItem {
  id: string
  productId: string
  productName: string
  productSlug: string
  productImage: string
  price: number
  quantity: number
  variant?: {
    size?: string
    color?: string
    sku: string
  }
  stock: number
}

// ==================== SEARCH TYPES ====================

export interface SearchResults {
  products: Product[]
  brands: Array<{ id: string; name: string; logo?: string }>
  articles: Array<{
    id: string
    title: string
    excerpt: string
    image?: string
    url: string
  }>
  videos: Array<{
    id: string
    title: string
    thumbnail: string
    duration: string
    url: string
  }>
}

// ==================== FAQ TYPES ====================

export interface FAQ {
  id: string
  question: string
  answer: string
  category: string
  order: number
  views: number
  helpful: number
  notHelpful: number
  relatedFAQs?: string[]
}

export interface FAQCategory {
  id: string
  name: string
  icon: string
  count: number
}

// ==================== TAG TYPES ====================

export interface Tag {
  id: string
  name: string
  slug: string
}

// ==================== GAMIFICATION TYPES ====================

export interface LoyaltyTier {
  name: 'Bronze' | 'Silver' | 'Gold' | 'Platinum'
  pointsRequired: number
  benefits: string[]
}

// ==================== API RESPONSE TYPES ====================

export interface ApiResponse<T> {
  data: T
  success: boolean
  error?: string
}

export interface PaginatedResponse<T> {
  data: T[]
  totalCount: number
  page: number
  pageSize: number
  hasMore: boolean
}

// ==================== HEADER TYPES ====================

export interface HeaderConfig {
  heights: {
    promotionalBanner: number
    topBar: number
    mainHeader: number
    categoryNavBar: number
    total: number
    compact: number
  }
  scrollThresholds: {
    hide: number
    compact: number
  }
}

export interface Language {
  code: string
  name: string
  nativeName: string
  flag: string
}

export interface Currency {
  code: string
  symbol: string
  name: string
  rate: number
}

export interface RotatingMessage {
  id: string
  text: string
  icon?: string
  link?: string
  type?: 'info' | 'success' | 'warning' | 'promo'
}

export interface Notification {
  id: string
  type: 'order' | 'promo' | 'system' | 'message'
  title: string
  message: string
  icon?: string
  timestamp: Date
  read: boolean
  link?: string
}

export interface GeolocationData {
  country: string
  city: string | null
  region: string | null
  countryCode: string
  currency: string
  timezone: string
}

export interface UserPreferences {
  language: string
  currency: string
  theme: 'light' | 'dark' | 'system'
  location?: string
  notifications?: boolean
  reducedMotion?: boolean
}

export interface ComparatorItem {
  id: string
  name: string
  price: number
  image: string
  category: string
  addedAt: Date
}

export interface MegaMenuColumn {
  id: string
  title: string
  icon?: string
  description?: string
  link: string
  image?: string
  subcategories?: {
    id: string
    title: string
    link: string
    items?: {
      id: string
      title: string
      link: string
      badge?: string
    }[]
  }[]
}

export interface SearchFilters {
  query: string
  category?: string
  minPrice?: number
  maxPrice?: number
  inStock?: boolean
  sortBy?: 'relevance' | 'price-asc' | 'price-desc' | 'newest' | 'rating'
}

export interface SearchSuggestion {
  type: 'product' | 'category' | 'brand' | 'keyword'
  title: string
  subtitle?: string
  image?: string
  link: string
}

export interface VisualSearchResult {
  confidence: number
  product: Product
}
