/**
 * Centralized TypeScript types for the entire application
 */

import type { ReactNode } from 'react'

// Note: @/payload/payload-types will be auto-generated by Payload CMS on first run
// Uncomment the line below after running `npm run dev` for the first time



// ==================== PRODUCT TYPES ====================

export interface ProductVariant {
  id: string
  size?: string
  color?: string
  sku: string
  stock: number
  priceModifier?: number
  image?: string
}

export interface Product {
  id: string
  name: string
  slug: string
  price: number
  compareAtPrice?: number
  images: ProductImage[]
  variants?: ProductVariant[]
  category: Category
  tags?: Tag[]
  rating: number
  reviewCount: number
  stock: number
  badge?: string
  featured?: boolean
  onSale?: boolean
  description?: string
  specifications?: Record<string, string>
  seo?: {
    title: string
    description: string
    keywords?: string[]
  }
  arModelUrl?: string // URL to 3D model for AR preview
  bundleProducts?: BundleProduct[] // Frequently bought together
  shippingInfo?: ShippingInfo
  faqs?: FAQ[]
  vendor?: {
    id: string
    name?: string // For PLP/category pages (light serialization)
    businessName?: string // For PDP (full serialization)
    slug?: string // For PDP (full serialization)
  }
}

export interface ProductImage {
  url: string
  alt: string
  type: 'image' | 'video' | '360'
  thumbnail?: string
  videoUrl?: string // For video type
  frames?: string[] // For 360 type (array of frame URLs)
}

// ==================== CATEGORY TYPES ====================

export interface Category {
  id: string
  name: string
  slug: string
  description?: string
  image?: string
  parent?: {
    name: string
    slug: string
  }
  order?: number
  isActive: boolean
  productCount?: number
}

// ==================== ORDER TYPES ====================

export type OrderStatus = 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled'
export type PaymentStatus = 'pending' | 'paid' | 'failed' | 'refunded'
export type PaymentGateway = 'PAYSTACK' | 'FLUTTERWAVE'

export interface OrderItem {
  id?: string
  productId: string
  name: string
  productImage: string
  variant?: {
    size?: string
    color?: string
    sku: string
  }
  quantity: number
  price: number
  subtotal: number
}

export interface Address {
  firstName: string
  lastName: string
  line1: string
  line2?: string
  city: string
  postalCode: string
  country: string
  phone: string
  email?: string
  isDefault?: boolean
  orderNotes?: string // Instructions de livraison (max 500 caractères)
}

export interface SavedAddress extends Address {
  id: string
  userId: string
  isDefault: boolean
  createdAt: Date
  updatedAt: Date
}

export interface Order {
  id: string
  orderNumber: string
  userId: string
  items: OrderItem[]
  status: OrderStatus
  paymentStatus: PaymentStatus
  paymentReference?: string // Paystack reference ou Flutterwave tx_ref
  paymentGateway?: PaymentGateway
  paymentMetadata?: Record<string, unknown>
  subtotal: number
  shippingCost: number
  shippingTotal?: number
  tax: number
  taxTotal?: number
  discount: number
  total: number
  shippingAddress: Address
  billingAddress?: Address
  trackingNumber?: string
  estimatedDelivery?: {
    min: Date
    max: Date
  } | Date
  createdAt: Date
  updatedAt: Date
  couponCode?: string
  customer?: {
    firstName: string
    lastName: string
    email: string
  }
  shipping?: {
    method: string
    cost: number
    estimatedDelivery: Date
    address: Address
  }
  payment?: {
    type: PaymentMethod
    brand?: string
    last4?: string
  }
  shippingMethod?: string
  paymentType?: PaymentMethod
  paymentBrand?: string
  paymentLast4?: string
}

// ==================== USER TYPES ====================

export interface User {
  id: string
  email: string
  firstName?: string
  lastName?: string
  addresses?: Address[]
  loyaltyPoints?: number
  loyaltyLevel?: 'Bronze' | 'Silver' | 'Gold' | 'Platinum'
  recentlyViewed?: string[]
  searchHistory?: string[]
  totals?: {
    orders: number
    spent: number
  }
}

// ==================== REVIEW TYPES ====================

/**
 * Merchant response to a customer review
 */
export interface MerchantResponse {
  text: string
  respondedAt: string | Date
  respondedBy?: string
}

export interface Review {
  id: string
  productId: string
  userId: string
  userName: string
  userAvatar?: string
  rating: number
  title?: string
  comment: string
  images?: string[]
  videos?: string[] // Array of video URLs
  verified: boolean
  helpful: number
  notHelpful: number
  createdAt: Date
  response?: MerchantResponse
}

export interface ReviewStats {
  average: number
  total: number
  distribution: {
    5: number
    4: number
    3: number
    2: number
    1: number
  }
}

// ==================== FILTER TYPES ====================

export interface Filter {
  priceRange?: {
    min: number
    max: number
  }
  categories?: string[]
  brands?: string[]
  colors?: string[]
  sizes?: string[]
  rating?: number
  inStock?: boolean
  onSale?: boolean
}

export interface AvailableFilters {
  priceRange: {
    min: number
    max: number
  }
  categories: Array<{ id: string; name: string; count: number }>
  brands: Array<{ id: string; name: string; count: number }>
  colors: Array<{ value: string; name: string; count: number }>
  sizes: Array<{ value: string; count: number }>
}

// Popularity sorting uses calculated engagement score (views * weight + sales * weight)
export type SortOption = 'relevance' | 'price-asc' | 'price-desc' | 'rating' | 'newest' | 'bestseller' | 'popularity'

// ==================== PLP TYPES ====================

export interface BreadcrumbItem {
  label: string
  href?: string
}

export interface QuickFilter {
  id: string
  label: string
  value: string
}

export interface CategoryHeroData {
  title: string
  description?: string
  image?: string
  productCount: number
  quickFilters?: QuickFilter[]
}

export interface FilterSection {
  id: string
  title: string
  isOpen: boolean
}

export interface PriceHistogramBin {
  min: number
  max: number
  count: number
}

export interface RecentlyViewedProduct {
  productId: string
  viewedAt: string
}

// ==================== SHIPPING TYPES ====================

export interface ShippingOption {
  id: string
  name: string
  price: number
  estimatedDays: number
  carrier?: string
  cutoffTime?: string
  description?: string
}

export interface ShippingInfo {
  options: Array<{
    name: string
    price: number
    estimatedDays: number
    description?: string
  }>
  freeShippingThreshold?: number
  internationalShipping: boolean
  returnPolicy: string
}

// ==================== TAX & SHIPPING CALCULATION TYPES ====================

/**
 * Delivery zones for tax and shipping calculation (Pan-African Platform)
 *
 * Regional groupings based on African economic communities:
 * - WEST_AFRICA: ECOWAS/CEDEAO countries (Nigeria, Côte d'Ivoire, Ghana, Senegal, etc.)
 * - CENTRAL_AFRICA: CEMAC/ECCAS countries (Cameroon, Gabon, DR Congo, etc.)
 * - EAST_AFRICA: EAC countries (Kenya, Tanzania, Uganda, Rwanda, etc.)
 * - SOUTHERN_AFRICA: SADC countries (South Africa, Zimbabwe, Botswana, etc.)
 * - NORTH_AFRICA: UMA countries (Morocco, Algeria, Tunisia, Egypt, Libya)
 * - INTERNATIONAL: Rest of the world (Europe, Americas, Asia, etc.)
 */
export type DeliveryZone = 'WEST_AFRICA' | 'CENTRAL_AFRICA' | 'EAST_AFRICA' | 'SOUTHERN_AFRICA' | 'NORTH_AFRICA' | 'INTERNATIONAL'

/**
 * Tax calculation result with zone detection
 */
export interface TaxCalculationResult {
  /** Tax rate in percentage (e.g., 20 for 20%) */
  taxRate: number
  /** Tax amount in cents */
  taxAmount: number
  /** Detected delivery zone */
  zone: DeliveryZone
  /** ISO country code */
  country: string
  /** Whether the country is in the EU */
  isEU: boolean
}

/**
 * Shipping cost calculation result
 */
export interface ShippingCalculationResult {
  /** Shipping cost in cents */
  cost: number
  /** Delivery zone */
  zone: DeliveryZone
  /** Estimated delivery days (business days) */
  estimatedDays: number
  /** Whether free shipping was applied */
  freeShippingApplied: boolean
  /** Optional weight surcharge in cents */
  weightSurcharge?: number
}

/**
 * Complete totals calculation result
 */
export interface TotalsCalculationResult {
  /** Subtotal in cents */
  subtotal: number
  /** Shipping calculation details */
  shipping: ShippingCalculationResult
  /** Tax calculation details */
  tax: TaxCalculationResult
  /** Discount amount in cents */
  discount: number
  /** Total amount in cents */
  total: number
  /** Free shipping threshold in cents */
  freeShippingThreshold?: number
  /** Amount remaining to qualify for free shipping in cents */
  amountToFreeShipping?: number
}

/**
 * Payload for calculate totals API endpoint
 */
export interface CalculateTotalsPayload {
  /** Cart items */
  items: Array<{
    productId: string
    quantity: number
    variantId?: string
  }>
  /** Shipping address */
  address: Address
  /** Selected shipping option ID */
  shippingOptionId?: string
  /** Optional coupon code */
  couponCode?: string
}

// Simplified product for bundle display
export interface BundleProductInfo {
  id: string
  name: string
  slug: string
  price: number
  images: Array<{ url: string; alt: string }>
}

export interface BundleProduct {
  product: Product | BundleProductInfo
  discount?: number // Percentage discount when bought together
}

export interface RelayPoint {
  id: string
  name: string
  address: string
  city: string
  postalCode: string
  distance: number
  openingHours?: string[]
  coordinates?: {
    lat: number
    lng: number
  }
}

export interface Store {
  id: string
  name: string
  address: string
  city: string
  postalCode: string
  distance: number
  phone?: string
  openingHours?: string[]
}

// ==================== PAYMENT TYPES ====================

export type PaymentMethod = 'card' | 'paypal' | 'apple-pay' | 'google-pay' | 'installments'

export interface PaymentIntent {
  id: string
  clientSecret: string
  amount: number
  currency: string
  status: string
}

// ==================== CART TYPES ====================

export interface CartItem {
  id: string
  productId: string
  name?: string
  productName?: string
  productSlug: string
  productImage: string
  image?: string
  price: number
  quantity: number
  variant?: {
    size?: string
    color?: string
    sku: string
  }
  stock: number
  badge?: string // Promotional badges (e.g., 'NEW', 'SALE')
  freeShipping?: boolean // Item qualifies for free shipping
  inStock?: boolean // Stock availability (optional for backward compatibility)
  maxQuantity?: number // Maximum quantity that can be ordered
  compareAtPrice?: number // Original price before discount
  category?: string
  brand?: string
}

export interface SavedForLaterItem extends CartItem {
  savedAt: string | Date
}

export interface CouponCode {
  code: string
  discount: number
  type: 'percentage' | 'fixed'
  scope: 'cart' | 'shipping' // Determines whether coupon applies to items or shipping
  minPurchase?: number
  expiresAt?: string | Date
}

export type PromotionType = 'automatic' | 'manual' | 'sale' | 'new'

export interface AppliedPromotion {
  id: string
  type: PromotionType
  code?: string // Code promo si type='manual'
  label: string // Label affiché (ex: "Promo Flash", "Code promo")
  description?: string // Description courte
  /**
   * Discount amount in CENTS (absolute monetary value after calculation).
   * This field always represents the actual monetary savings, regardless of how the discount was originally defined.
   * For example, a 20% discount on a €50 cart would have discount = 1000 (€10 in cents).
   */
  discount: number
  /**
   * The type of discount as originally defined (percentage or fixed amount).
   * This is for display purposes and to understand the source of the discount.
   * The actual monetary value is always stored in the `discount` field above.
   */
  discountType: 'percentage' | 'fixed'
  scope: 'cart' | 'shipping' | 'item' // Portée de la promotion
  appliedTo?: string[] // IDs des produits concernés (pour promotions par item)
  expiresAt?: Date // Date d'expiration
  conditions?: string // Conditions d'application (ex: "Minimum 50€")
}

export interface PromotionBadgeProps {
  type: PromotionType
  label: string
  discount?: string // Format: "-20%" ou "-5€"
  icon?: ReactNode
  size?: 'sm' | 'md' | 'lg'
  className?: string
}

export interface SavingsSummaryProps {
  subtotal: number // Montant avant réductions en cents
  discount: number // Montant total des réductions en cents
  finalTotal: number // Montant après réductions en cents
  showConfetti?: boolean // Déclenche l'animation confetti
  className?: string
}

export interface CartRecommendation {
  productId: string
  relevanceScore: number
  reason?: string // e.g., 'frequently bought together', 'similar category'
}

// ==================== SEARCH TYPES ====================

export interface SearchResults {
  products: Product[]
  brands: Array<{ id: string; name: string; logo?: string }>
  articles: Array<{
    id: string
    title: string
    excerpt: string
    image?: string
    url: string
  }>
  videos: Array<{
    id: string
    title: string
    thumbnail: string
    duration: string
    url: string
  }>
  correctedQuery?: string // The corrected search query that was used
  originalQuery?: string // The original user query before correction
  searchMetadata?: SearchMetadata // Metadata about the search execution
}

// ==================== UNIFIED SEARCH SERVICE TYPES ====================

export type SearchEngineType = 'postgresql' | 'meilisearch'
export type SearchVariant = 'postgresql' | 'meilisearch'

export interface SearchMetadata {
  searchEngine: SearchEngineType
  executionTime: number
  cacheHit?: boolean
  abTestVariant?: SearchVariant
  usedFTS?: boolean // Deprecated, use searchEngine instead
  usedFuzzy?: boolean
  facetsExecutionTime?: number
  searchLocale?: SupportedLocale
}

// Cache Metrics Types

/**
 * Represents cache performance metrics for a specific cache tier
 */
export interface CacheMetrics {
  keyPrefix: string
  hits: number
  misses: number
  hitRate: number // percentage (0-100)
  avgLatency: number // milliseconds
  totalRequests: number
}

/**
 * Aggregated cache metrics for all tiers (suggestions, search, facets)
 */
export interface CacheTierMetrics {
  suggestions: CacheMetrics
  search: CacheMetrics
  facets: CacheMetrics
  overall: {
    totalHits: number
    totalMisses: number
    overallHitRate: number
    avgLatency: number
  }
}

/**
 * Additional cache statistics including Redis status and invalidation data
 */
export interface CacheStats {
  redis: {
    connected: boolean
    usedMemory: string // e.g., "15.2 MB"
    totalKeys: number
    evictedKeys: number
  }
  topCachedQueries: Array<{
    query: string
    hits: number
    lastAccessed: string
  }>
  invalidationStats: {
    lastInvalidation: string | null
    totalInvalidations: number
  }
}

/**
 * Response structure for the admin cache metrics API endpoint
 */
export interface SearchCacheMetricsResponse {
  metrics: CacheTierMetrics
  stats: CacheStats
  period: {
    startTime: string
    endTime: string
    durationHours: number
  }
}

// Cache Warming Types

/**
 * Configuration options for cache warming operations
 */
export interface WarmCacheOptions {
  topQueries?: number
  periodDays?: number
  onProgress?: (current: number, total: number) => void
  sessionId?: string
}

/**
 * Result summary of a cache warming operation
 */
export interface WarmCacheResult {
  total: number
  warmed: number
  failed: number
  duration: number
  errors: Array<{
    query: string
    error: string
  }>
}

export interface SearchPerformanceData {
  sessionId: string
  variant: SearchVariant
  query: string
  executionTime: number
  resultCount: number
  timestamp: Date
}

export interface ABTestMetrics {
  postgresql: {
    totalSearches: number
    avgExecutionTime: number
    p50Latency: number
    p95Latency: number
    p99Latency: number
    avgResultCount: number
    zeroResultRate: number
  }
  meilisearch: {
    totalSearches: number
    avgExecutionTime: number
    p50Latency: number
    p95Latency: number
    p99Latency: number
    avgResultCount: number
    zeroResultRate: number
  }
  comparison: {
    speedImprovement: number // percentage
    winner: 'postgresql' | 'meilisearch' | 'tie'
  }
}

// ==================== FAQ TYPES ====================

export interface FAQ {
  id: string
  question: string
  answer: string
  category: string
  order: number
  views: number
  helpful: number
  notHelpful: number
  relatedFAQs?: string[]
}

export interface FAQCategory {
  id: string
  name: string
  icon: string
  count: number
}

export interface QA {
  id: string
  question: string
  answer: string // Kept for backward compatibility with FAQ data
  helpful: number
  notHelpful?: number
  createdAt?: Date
  // Enhanced Q&A fields
  author?: {
    name: string
    avatar?: string
  }
  answers?: Array<{
    id: string
    text: string
    author: {
      name: string
      avatar?: string
    }
    isOfficial: boolean
    createdAt: Date
    helpful: number
    notHelpful: number
  }>
  askedAt?: Date
  verified?: boolean // Verified purchase question
}

// ==================== TAG TYPES ====================

export interface Tag {
  id: string
  name: string
  slug: string
}

// ==================== GAMIFICATION TYPES ====================

export interface LoyaltyTier {
  name: 'Bronze' | 'Silver' | 'Gold' | 'Platinum'
  pointsRequired: number
  benefits: string[]
}

// ==================== API RESPONSE TYPES ====================

export interface ApiResponse<T> {
  data: T
  success: boolean
  error?: string
}

export interface PaginatedResponse<T> {
  data: T[]
  totalCount: number
  page: number
  pageSize: number
  hasMore: boolean
}

// ==================== HEADER TYPES ====================

export interface HeaderConfig {
  heights: {
    promotionalBanner: number
    topBar: number
    mainHeader: number
    categoryNavBar: number
    total: number
    compact: number
  }
  scrollThresholds: {
    hide: number
    compact: number
  }
}

export interface Language {
  code: string
  name: string
  nativeName: string
  flag: string
}

export interface Currency {
  code: string
  symbol: string
  name: string
  rate: number
}

export interface RotatingMessage {
  id: string
  text: string
  icon?: string
  link?: string
  type?: 'info' | 'success' | 'warning' | 'promo'
}

export interface Notification {
  id: string
  type: 'order' | 'promo' | 'system' | 'message'
  title: string
  message: string
  icon?: string
  timestamp: Date
  read: boolean
  link?: string
}

export interface GeolocationData {
  country: string
  city: string | null
  region: string | null
  countryCode: string
  currency: string
  timezone: string
}

export interface UserPreferences {
  language: string
  currency: string
  theme: 'light' | 'dark' | 'system'
  location?: string
  notifications?: boolean
  reducedMotion?: boolean
}

export interface ComparatorItem {
  id: string
  name: string
  price: number
  image: string
  category: string
  addedAt: Date
}

export interface MegaMenuColumn {
  id: string
  title: string
  icon?: string
  description?: string
  link: string
  image?: string
  subcategories?: {
    id: string
    title: string
    link: string
    items?: {
      id: string
      title: string
      link: string
      badge?: string
    }[]
  }[]
}

export interface SearchFilters {
  query: string
  category?: string
  minPrice?: number
  maxPrice?: number
  inStock?: boolean
  sortBy?: 'relevance' | 'price-asc' | 'price-desc' | 'newest' | 'rating'
}

export interface SearchSuggestion {
  type: 'product' | 'category' | 'brand' | 'keyword'
  title: string
  subtitle?: string
  image?: string
  link: string
}

export interface SearchHistoryEntry {
  query: string
  timestamp: Date
}

export interface SearchHistoryResponse {
  data: SearchHistoryEntry[]
  success: boolean
}

export interface VisualSearchResult {
  confidence: number
  product: Product
}

// ==================== CHECKOUT TYPES ====================

export type CheckoutStep = 'shipping' | 'payment' | 'review'

export interface TrustBadge {
  icon: string
  title: string
  description: string
}

export interface ShippingFormData {
  firstName: string
  lastName: string
  email: string
  phone: string
  line1: string
  line2?: string
  city: string
  postalCode: string
  country: string
  saveAddress?: boolean
  orderNotes?: string // Instructions de livraison (max 500 caractères)
}

export interface PaymentFormData {
  cardNumber: string
  expiryDate: string
  cvv: string
  cardholderName: string
  saveCard?: boolean
  billingAddressSameAsShipping?: boolean
  billingAddress?: Address
}

export interface BillingAddressFormData extends Address {
  sameAsShipping: boolean
}

// ==================== PAYMENT GATEWAY TYPES ====================

export interface PaystackInitializeResponse {
  success: boolean
  gateway: 'PAYSTACK'
  reference: string
  authorization_url: string
  access_code: string
  amount?: number // For display
  metadata?: Record<string, unknown>
}

export interface FlutterwaveInitializeResponse {
  success: boolean
  gateway: 'FLUTTERWAVE'
  tx_ref: string
  link: string
  amount?: number // For display
  metadata?: Record<string, unknown>
}

export type PaymentInitializeResponse =
  | PaystackInitializeResponse
  | FlutterwaveInitializeResponse

// ==================== ORDER INITIALIZATION TYPES ====================

export interface OrderInitializePayload {
  items: Array<{
    productId: string
    variantId?: string
    quantity: number
  }>
  shippingAddress: Address
  billingAddress?: Address
  shippingOption?: string
  gateway?: PaymentGateway
  email?: string
  promoCode?: string
  orderId?: string // For updating existing provisional order
  orderNotes?: string // Instructions de livraison
}

export interface OrderInitializeResponse {
  success: boolean
  orderId: string
  orderNumber: string
  totals: {
    subtotal: number // in cents
    shippingCost: number // in cents
    tax: number // in cents
    discount: number // in cents
    total: number // in cents
  }
  provisional: boolean
}

// ==================== PAYMENT INITIALIZATION TYPES ====================

export interface InitializePaymentPayload {
  items?: Array<{
    productId: string
    variantId?: string
    quantity: number
  }>
  shippingOption?: string
  email?: string
  orderId?: string // If provisional order already created
  gateway: PaymentGateway
  metadata?: Record<string, unknown>
}

// ==================== ORDER COMPLETION TYPES ====================

export interface OrderCompletePayload {
  paymentReference: string
  paymentGateway: PaymentGateway
  billingAddress?: Address
  promoCode?: string
  orderNotes?: string // Instructions de livraison
}

export interface OrderCompleteResponse {
  success: boolean
  orderId: string
  orderNumber: string
  status: OrderStatus
  paymentStatus: PaymentStatus
  message?: string
}

// ==================== WEBHOOK TYPES ====================

export interface InitializePaymentResponse {
  success: boolean
  gateway: 'PAYSTACK' | 'FLUTTERWAVE'
  reference?: string // Paystack reference
  authorization_url?: string // Paystack redirect URL
  tx_ref?: string // Flutterwave transaction reference
  link?: string // Flutterwave payment link
  amount: number
  orderId?: string
  error?: string
}

export interface WebhookMetadata {
  orderId?: string
  userId?: string
  items?: string // JSON string of cart items
  subtotal?: string
  shippingCost?: string
  tax?: string
  total?: string
  [key: string]: unknown
}

export interface PaystackWebhookEvent {
  event: string // e.g., 'charge.success', 'charge.failed'
  data: {
    reference: string
    amount: number // in kobo
    customer: {
      email: string
      [key: string]: unknown
    }
    metadata?: WebhookMetadata
    [key: string]: unknown
  }
}

export interface FlutterwaveWebhookEvent {
  event: string // e.g., 'charge.completed', 'charge.failed'
  data: {
    id: number | string
    tx_ref: string
    amount: number // in currency unit
    customer: {
      email?: string
      customer_email?: string
      phone?: string
      phone_number?: string
      [key: string]: unknown
    }
    meta?: WebhookMetadata
    metadata?: WebhookMetadata
    [key: string]: unknown
  }
}

// ==================== SEARCH ANALYTICS TYPES ====================

// Supported locales for multilingual search
export type SupportedLocale = 'fr' | 'en'

export interface SearchLogEntry {
  id: string
  query: string
  resultCount: number
  userId?: string | null
  sessionId?: string | null
  filters?: Record<string, unknown> | null
  sort?: string | null
  executionTime?: number | null
  clickedProductId?: string | null
  clickPosition?: number | null
  clickedAt?: Date | null
  ipAddress?: string | null
  userAgent?: string | null
  correctedFrom?: string | null
  locale?: SupportedLocale
  timestamp: Date
}

export interface TopQuery {
  query: string
  count: number
  avgResultCount: number
  clickThroughRate: number
}

export interface ZeroResultQuery {
  query: string
  count: number
  lastSearched: Date
}

export interface SearchTrend {
  timestamp: Date
  count: number
  uniqueUsers: number
}

export interface ProductClickStats {
  productId: string
  clicks: number
  avgPosition: number
  queries: string[]
}

export interface SearchAnalyticsReport {
  topQueries: TopQuery[]
  zeroResultQueries: ZeroResultQuery[]
  overallCTR: number
  totalSearches: number
  uniqueUsers: number
  avgResultCount: number
  trends: SearchTrend[]
  period: {
    startDate: string
    endDate: string
  }
  productStats?: ProductClickStats[]
}

// Dashboard-specific analytics types
export interface CTRByQuery {
  query: string
  ctr: number
  searches: number
  clicks: number
}

export interface LocaleDistribution {
  locale: SupportedLocale | 'other'
  count: number
  percentage: number
}

export interface SearchEngineComparison {
  postgresql: {
    searches: number
    avgExecutionTime: number
    avgResultCount: number
  }
  meilisearch: {
    searches: number
    avgExecutionTime: number
    avgResultCount: number
  }
  winner: 'postgresql' | 'meilisearch' | 'tie'
}

export interface PeriodComparison {
  current: {
    totalSearches: number
    overallCTR: number
    avgResultCount: number
  }
  previous: {
    totalSearches: number
    overallCTR: number
    avgResultCount: number
  }
  changes: {
    searchesChange: number
    ctrChange: number
    resultsChange: number
  }
}

export interface DashboardAnalyticsReport extends SearchAnalyticsReport {
  ctrByQuery: CTRByQuery[]
  localeDistribution: LocaleDistribution[]
  /** @future Search engine comparison (PostgreSQL vs MeiliSearch) - not yet implemented */
  searchEngineComparison?: SearchEngineComparison
  periodComparison?: PeriodComparison
}

// ==================== CUSTOMER 360 TYPES ====================

export * from './customer-360'

// ==================== PERSONALIZATION TYPES ====================

export * from './personalization'
